version: "3"

tasks:
  goose-up:
    desc: "up migrations"
    dotenv: ['.env']
    cmds:
       - goose -dir ./migrations postgres "host=$POSTGRES_HOST user=$POSTGRES_USER password=$POSTGRES_PASSWORD dbname=$POSTGRES_DB port=$POSTGRES_PORT sslmode=disable" up
  goose-down:
    desc: "down migrations"
    dotenv: ['.env']
    cmds:
       - goose -dir ./migrations postgres "host=$POSTGRES_HOST user=$POSTGRES_USER password=$POSTGRES_PASSWORD dbname=$POSTGRES_DB port=$POSTGRES_PORT sslmode=disable" down
  run:
    desc: "run application"
    deps: ["goose-up"]
    cmds:
       - go run ./cmd/url-shortener/main.go

  goose-up-docker:
    desc: "up migrations in db container"
    dotenv: ['.env.compose']
    vars:
      DBSTRING: "host=$POSTGRES_HOST user=$POSTGRES_USER password=$POSTGRES_PASSWORD dbname=$POSTGRES_DB port=5432 sslmode=disable"
    cmds:
      - docker run -t migrator:v1 goose -dir /migrations postgres "{{.DBSTRING}}" up
