version: "3.8"

services:
  app:
    build:
      context: ../
      dockerfile: ./cmd/url-shortener/Dockerfile
    command: ./cmd/url-shortener/app
    env_file:
      - ./.env
    ports:
      - ${OUT_HTTP_PORT}:8080
    depends_on:
      - db
      - migrator

  migrator:
    container_name: migrator
    build:
      context: ../
      dockerfile: ./migrations/Dockerfile
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    container_name: db
    restart: always
    image: postgres:latest
    env_file:
      - ./.env
    ports:
      - 5436:${POSTGRES_PORT}
