env: "local" # local, dev, prod and etc
postgres:
  host: "localhost"
  port: 5432
  user: "chaykovski"
  database_name: "url_shortener"
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s