env: "prod" # local, dev, prod and etc
postgres:
  host: "0.0.0.0"
  port: 5432
  user: "chaykovski"
  database_name: "test"
http_server:
  address: "0.0.0.0:8080"
  timeout: 4s
  idle_timeout: 60s
  user: "chaykovski"